//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    [MetadataType(typeof(Factor_DetailsMetaData))]
    public partial class Factor_Details
    {
        public int DetailID { get; set; }
        public int FactorID { get; set; }
        public int ProductID { get; set; }
        public int Price { get; set; }
        public int Count { get; set; }
        public int Sum { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Factors Factors { get; set; }
    }
}
