//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    [MetadataType(typeof(FactorsMetaData))]
    public partial class Factors
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Factors()
        {
            this.Factor_Details = new HashSet<Factor_Details>();
        }
    
        public int FactorID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> AddressID { get; set; }
        public System.DateTime Date { get; set; }
        public bool IsFinally { get; set; }
        public int TotalPrice { get; set; }
        public int StatusID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Factor_Details> Factor_Details { get; set; }
        public virtual FactorStautus FactorStautus { get; set; }
        public virtual User_Address User_Address { get; set; }
        public virtual Users Users { get; set; }
    }
}
