//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    [MetadataType(typeof(Order_FilesMetaData))]
    public partial class Order_Files
    {
        public int OF_ID { get; set; }
        public int OT_ID { get; set; }
        public string FileName { get; set; }
    
        public virtual Order_Details Order_Details { get; set; }
    }
}
