//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    [MetadataType(typeof(Order_DetailsMetaData))]
    public partial class Order_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order_Details()
        {
            this.Order_Files = new HashSet<Order_Files>();
        }
    
        public int OT_ID { get; set; }
        public int OrderID { get; set; }
        public string FrontText { get; set; }
        public string BackText { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsDesigned { get; set; }
        public int Count { get; set; }
        public string SocialNumber { get; set; }
        public System.DateTime OrderDate { get; set; }
    
        public virtual Products Products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Files> Order_Files { get; set; }
    }
}
