//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    [MetadataType(typeof(Product_GroupsMetaData))]
    public partial class Product_Groups
    {
        public int PG_ID { get; set; }
        public int ProductID { get; set; }
        public Nullable<int> ST_GroupID { get; set; }
        public Nullable<int> Order_GroupID { get; set; }
    
        public virtual Order_Groups Order_Groups { get; set; }
        public virtual Products Products { get; set; }
        public virtual School_Tools_Groups School_Tools_Groups { get; set; }
    }
}
