//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    [MetadataType(typeof(UserAddressMetaData))]
    public partial class UserAddress
    {

        public int AddressID { get; set; }
        public int UserID { get; set; }
        public int ProvinceID { get; set; }
        public int CityID { get; set; }
        public string FullName { get; set; }
        public string FullAddress { get; set; }
        public string PosteCode { get; set; }
    
        public virtual city city { get; set; }
        public virtual province province { get; set; }
        public virtual User Users { get; set; }
    }
}
