//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    [MetadataType(typeof(User_AddressMetaData))]
    public partial class User_Address
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User_Address()
        {
            this.Factors = new HashSet<Factors>();
        }
    
        public int AddressID { get; set; }
        public int UserID { get; set; }
        public int ProvinceID { get; set; }
        public int CityID { get; set; }
        public string FullName { get; set; }
        public string FullAddress { get; set; }
        public string PosteCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Factors> Factors { get; set; }
        public virtual User Users { get; set; }
        public virtual city city { get; set; }
        public virtual province province { get; set; }
    }
}
