//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace DataLayer
{
    public class cityMetaData
    {
        [Key]
        public int cityId { get; set; }
        public int province_id { get; set; }
        public int county_id { get; set; }
        [Display(Name="شهر")]
        public string cityName { get; set; }
    }
}