//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace DataLayer
{
    public class ContactUsMetaData
    {
        [Key]
        public int CU_ID { get; set; }
        [Display(Name ="نام و نام خانوادگی")][Required(ErrorMessage = "لطفا {0} را وارد کنید")]
        public string FullName { get; set; }
        [Display(Name ="شماره تلفن")][RegularExpression(@"^([+]?\d{1,2}[-\s]?|)\d{3}[-\s]?\d{3}[-\s]?\d{4}|^([\w-]+(?:\.[\w-]+)*)@((?:[\w-]+\.)*\w[\w-]{0,66})\.([a-z]{2,6}(?:\.[a-z]{2})?)", ErrorMessage = "{0} معتبر نمی باشد!")]
        public string PhoneNumber { get; set; }
        [Display(Name ="ایمیل")][DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        [Display(Name ="عنوان")][Required(ErrorMessage = "لطفا {0} را وارد کنید")]
        public string Title { get; set; }
        [Display(Name ="توضیحات")][Required(ErrorMessage = "لطفا {0} را وارد کنید")]
        [MaxLength(800,ErrorMessage ="شما مجاز به وارد کردن بیش از ۸۰۰ کاراکتر نمی باشید")]
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }
    }
}