//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace DataLayer
{
    public class Factor_DetailsMetaData
    {
        [Key]
        public int DetailID { get; set; }
        [Display(Name ="فاکتور")][Required(ErrorMessage = "لطفا {0} را وارد کنید")]
        public int FactorID { get; set; }
        [Display(Name = "محصول")]
        [Required(ErrorMessage = "لطفا {0} را وارد کنید")]
        public int ProductID { get; set; }
        [Display(Name ="قیمت")][Required(ErrorMessage = "لطفا {0} را وارد کنید")]
        public int Price { get; set; }
        [Display(Name ="تعداد")][Required(ErrorMessage = "لطفا {0} را وارد کنید")]
        public int Count { get; set; }
    }
}