//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations;

namespace DataLayer
{
    public class FactorsMetaData
    {
        [Key]
        public int FactorID { get; set; }
        [Display(Name = "کاربر")]
        [Required(ErrorMessage = "لطفا {0} را وارد کنید")]
        public int UserID { get; set; }
        [Display(Name = "آدرس")]
        public int AddressID { get; set; }
        [Display(Name = "تاریخ ثبت")]
        [Required(ErrorMessage = "لطفا {0} را وارد کنید")]
        public System.DateTime Date { get; set; }
        [Display(Name = "وضعیت")]
        public bool IsFinally { get; set; }
        [Display(Name = "قیمت کل")]
        [Required(ErrorMessage = "لطفا {0} را وارد کنید")]
        public int TotalPrice { get; set; }
        [Display(Name = "شماره تراکنش خرید")]
        public int Ref { get; set; }

    }
}