//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations;

namespace DataLayer
{
    public class Order_DetailsMetaData
    {
        [Key]
        public int OT_ID { get; set; }
        [Display(Name ="محصول")][Required(ErrorMessage = "لطفا {0} را وارد کنید")]
        public int ProductID { get; set; }
        [Display(Name="کاربر")]
        public int UserID { get; set; }

        [Display(Name ="متن رو")]
        public string FrontText { get; set; }
        [Display(Name ="متن پشت")]
        public string BackText { get; set; }
        [Display(Name = "توضیحات")]
        public string Description { get; set; }
        [Display(Name ="طرح آماده")]
        public bool IsDesigned { get; set; }
        [Display(Name ="تعداد")]
        public int Count { get; set; }
        [Display(Name ="شماره موبایل")]
        [Required(ErrorMessage = "لطفا {0} را وارد کنید")]
        public string SocialNumber { get; set; }
        [Display(Name ="تاریخ سفارش")]
        public System.DateTime OrderDate { get; set; }
    }
}