//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace DataLayer
{
    public class Order_FilesMetaData
    {
        [Key]
        public int OF_ID { get; set; }
        [Display(Name ="محصول")][Required(ErrorMessage = "لطفا {0} را وارد کنید")]
        public int OT_ID { get; set; }
        [Display(Name = "تصویر")]
        [Required(ErrorMessage = "لطفا {0} را وارد کنید")]
        [RegularExpression(@"([a-zA-Z0-9\s_\\.\-:])+(.psd|.pdd|.jpg|.jpeg|.png|.tiff|.tif|.pdf)$", ErrorMessage = "فایل انتخاب شده معتبر نمی باشد")]
        public string FileName { get; set; }
    }
}