//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace DataLayer
{
    public class Product_Selected_GroupsMetaData
    {
        [Key]
        public int PS_ID { get; set; }
        [Display(Name ="محصول")]
        public int ProductID { get; set; }
        [Display(Name = "گروه")]
        public int GroupID { get; set; }

    }
}