//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace DataLayer
{
    public class Product_AttributeMetaData
    {
        [Key]
        [Required(ErrorMessage = "لطفا {0} را وارد کنید")]
        [Display(Name ="محصول")]
        public int ProductID { get; set; }
        [Display(Name ="پشت و رو")]
        public bool IsTwoFace { get; set; }
        [Display(Name ="تعداد سری")]
        [Required(ErrorMessage = "لطفا {0} را وارد کنید")]
        public int Count { get; set; }
    }
}