//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace DataLayer
{
    public class RoleMetaData
    {
        [Key]
        public int RoleID { get; set; }
        [Display(Name ="عنوان نقش")][Required(ErrorMessage = "لطفا {0} را وارد کنید")]
        public string RoleTitle { get; set; }
        [Display(Name = "عنوان سیستمی نقش")]
        [Required(ErrorMessage = "لطفا {0} را وارد کنید")]

        public string RoleName { get; set; }
    }
}