//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace DataLayer
{
    public class ShopCartMetaData
    {
        [Key]
        public int SC_ID { get; set; }
        [Display(Name ="محصول")]
        public int ProductID { get; set; }
        [Display(Name = "کاربر")]
        public int UserID { get; set; }
        [Display(Name ="قیمت")]
        public int Price { get; set; }        
        [Display(Name ="تعداد")]
        public int Count { get; set; }
        [Display(Name ="جمع کل")]
        public int Sum { get; set; }
    }
}