//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace DataLayer
{
    public class SiteVisitMetaData
    {
        [Key]
        public int VisitID { get; set; }
        [Display(Name ="آی پی")]
        [Required(ErrorMessage = "لطفا {0} را وارد کنید")]
        public string IP { get; set; }
        [Display(Name ="تاریخ")]
        [Required(ErrorMessage = "لطفا {0} را وارد کنید")]
        public System.DateTime Date { get; set; }
    }
}