//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace DataLayer
{
    public class UserMetaData
    {
        public int UserID { get; set; }
        public int RoleID { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string ActiveCode { get; set; }
        public string Phone { get; set; }
        public string Password { get; set; }
        public bool IsEmailActive { get; set; }
        public bool IsPhoneActive { get; set; }
        [DisplayFormat(DataFormatString ="{0: yyyy/MM/dd}")]
        public System.DateTime RegisterDate { get; set; }
    }
}